#!/bin/bash
application="packer"
remote_zip="https://releases.hashicorp.com/packer/1.2.5/packer_1.2.5_linux_amd64.zip"
local_zip="/tmp/${application}.zip"
wget "${remote_zip}" -O "${local_zip}"
sudo unzip $local_zip -d /opt/${application}/
sudo ln -s /opt/${application}/${application} /usr/bin/${application}

